---
# Общие переменные для всех хостов.
vpn_subnet: 40
vpn_port: 1194
wan_interface: eth0
ssh_port: 22
allowed_management_ips:
  - 185.197.161.44
  - 193.42.109.24
  - 82.146.35.177
  - 91.227.136.24
vpn_network: "10.8.{{ vpn_subnet }}.0/24"
openvpn_tls_dir: /etc/openvpn
